---
- name: Deploy Cloud Resume Website to AWS
  hosts: localhost
  connection: local
  gather_facts: true
  
  vars:
    # Set default values to prevent undefined variable errors
    frontend_dir: "{{ ansible_env.PWD }}/frontend"
    
  tasks:
    # =========================================
    # Display Configuration
    # =========================================
    - name: Display deployment configuration
      debug:
        msg: |
          ========================================
          🚀 DEPLOYMENT CONFIGURATION
          ========================================
          S3 Bucket: {{ s3_bucket_name | default('not-specified') }}
          CloudFront Distribution ID: {{ cloudfront_distribution_id | default('not-specified') }}
          Frontend Directory: {{ frontend_dir }}
          ========================================
    
    # =========================================
    # Validate Required Variables
    # =========================================
    - name: Validate required variables
      assert:
        that:
          - s3_bucket_name is defined
          - s3_bucket_name != ""
        fail_msg: |
          ❌ Missing required configuration.
          Required: s3_bucket_name
          Received: {{ s3_bucket_name | default('undefined') }}
    
    # =========================================
    # Frontend Build Process
    # =========================================
    - name: Check if frontend directory exists
      stat:
        path: "{{ frontend_dir }}"
      register: frontend_dir_stat
    
    - name: Display frontend directory status
      debug:
        msg: |
          📁 Frontend Directory Status:
          Path: {{ frontend_dir }}
          Exists: {{ frontend_dir_stat.stat.exists | ternary('✅ Yes', '❌ No') }}
    
    - name: Create frontend directory if it doesn't exist
      file:
        path: "{{ frontend_dir }}"
        state: directory
        mode: '0755'
      when: not frontend_dir_stat.stat.exists
    
    - name: Check if package.json exists
      stat:
        path: "{{ frontend_dir }}/package.json"
      register: package_json_stat
    
    - name: Install Node dependencies (clean, reproducible)
      community.general.npm:
        path: "{{ frontend_dir }}"
        state: present
        production: false
        ci: true
      register: npm_install_result
      when: package_json_stat.stat.exists
    
    - name: Display npm install results
      debug:
        msg: |
          📦 NPM Install Results:
          Status: {{ npm_install_result.changed | ternary('✅ Dependencies installed/updated', '✅ Dependencies already up to date') }}
          Path: {{ frontend_dir }}
      when: package_json_stat.stat.exists
    
    - name: Skip npm install (no package.json found)
      debug:
        msg: "⚠️  No package.json found in {{ frontend_dir }}, skipping npm install"
      when: not package_json_stat.stat.exists
    
    # =========================================
    # AWS Deployment Tasks
    # =========================================
    - name: Build frontend for production
      command: npm run build
      args:
        chdir: "{{ frontend_dir }}"
      register: build_result
      changed_when: true
      when: package_json_stat.stat.exists
    
    - name: Display build results
      debug:
        msg: |
          🔨 Build Results:
          Status: {{ build_result.rc == 0 | ternary('✅ Build successful', '❌ Build failed') }}
          Output: {{ build_result.stdout | default('No output') }}
      when: package_json_stat.stat.exists and build_result is defined
    
    - name: Check if build directory exists
      stat:
        path: "{{ frontend_dir }}/dist"
      register: dist_dir_stat
    
    - name: Sync files to S3 bucket
      amazon.aws.s3_sync:
        bucket: "{{ s3_bucket_name }}"
        file_root: "{{ frontend_dir }}/dist"
        mime_map:
          .html: text/html
          .css: text/css
          .js: application/javascript
          .json: application/json
        delete: true
        cache_control: "public, max-age=31536000"
      register: s3_sync_result
      when: 
        - s3_bucket_name is defined 
        - s3_bucket_name != ""
        - dist_dir_stat.stat.exists
    
    - name: Display S3 sync results
      debug:
        msg: |
          📤 S3 Sync Results:
          Bucket: {{ s3_bucket_name }}
          Status: {{ s3_sync_result.changed | ternary('✅ Files synced', '✅ No changes needed') }}
          Files: {{ s3_sync_result.file_list | default([]) | length }} files processed
      when: s3_sync_result is defined
    
    - name: Skip S3 sync (no dist directory)
      debug:
        msg: "⚠️  No dist directory found at {{ frontend_dir }}/dist, skipping S3 sync"
      when: not dist_dir_stat.stat.exists
    
    - name: Invalidate CloudFront distribution
      amazon.aws.cloudfront_invalidation:
        distribution_id: "{{ cloudfront_distribution_id }}"
        target_paths:
          - "/*"
      register: cloudfront_result
      when: 
        - cloudfront_distribution_id is defined 
        - cloudfront_distribution_id != ""
        - cloudfront_distribution_id != "not-specified"
        - s3_sync_result is defined
        - s3_sync_result.changed
    
    - name: Display CloudFront invalidation results
      debug:
        msg: |
          🌐 CloudFront Invalidation:
          Distribution ID: {{ cloudfront_distribution_id }}
          Status: {{ cloudfront_result.changed | ternary('✅ Cache invalidated', '✅ No invalidation needed') }}
          Invalidation ID: {{ cloudfront_result.invalidation.id | default('N/A') }}
      when: cloudfront_result is defined
    
    - name: Skip CloudFront invalidation
      debug:
        msg: "ℹ️  CloudFront invalidation skipped (no distribution ID provided or no S3 changes)"
      when: 
        - cloudfront_distribution_id is not defined or cloudfront_distribution_id == "" or cloudfront_distribution_id == "not-specified"
    
    # =========================================
    # Deployment Summary
    # =========================================
    - name: Deployment summary
      debug:
        msg: |
          ========================================
          🎉 DEPLOYMENT COMPLETE
          ========================================
          S3 Bucket: {{ s3_bucket_name }}
          CloudFront: {{ cloudfront_distribution_id | default('Not configured') }}
          Files Synced: {{ s3_sync_result.changed | default(false) | ternary('Yes', 'No changes needed') }}
          Cache Invalidated: {{ cloudfront_result.changed | default(false) | ternary('Yes', 'Not needed') }}
          ========================================